<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.Master" AutoEventWireup="true" CodeBehind="CapgeminiDetailSearch.aspx.cs" Inherits="HR_PresentationLayer_ASP.NET.CapgeminiDetailSearch" %>
<asp:Content ID="Content1" ContentPlaceHolderID="cphBody" runat="server">
    <table>
       <tr>
           <td style="width:10%">

           </td>
           <td style="width:80%">
               <br />
               <table>
                   <tr>
                       <td style="width: auto">
                           <asp:Label runat="server">Search Detail: </asp:Label> 
               
                       </td>
                        <td style="width: auto">
                            <asp:DropDownList runat="server" ID="ddEmployeeID" CssClass="browser-default" Width="200px" OnSelectedIndexChanged="ddEmployeeID_SelectedIndexChanged" AutoPostBack="True" DataSourceID="SqlDataSource1" DataTextField="EmployeeID" DataValueField="EmployeeID"></asp:DropDownList>
               
                       
                            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="select EmployeeID from
balaji.CapgeminiDetails_HR_Batch4"></asp:SqlDataSource>
               
                       
                        </td>
                       <td>
                           <asp:Button ID="Button1" CssClass="waves-effect waves-light btn" runat="server" Text="Refresh" OnClick="Button1_Click"  />
                       </td>
                       <td>
                          <asp:HyperLink ID="btnAddNew" runat="server" CssClass="waves-effect waves-light btn" Text="Add New" NavigateUrl="~/CapgeminiDetailsControl.aspx" ></asp:HyperLink>
                       </td>
                   </tr>
               </table>
               <br />
               <asp:Panel ID="Panel1" runat="server">
                               <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource2">
                   <Columns>
                       <asp:BoundField DataField="EmployeeID" HeaderText="EmployeeID" SortExpression="EmployeeID" />
                       <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                       <asp:BoundField DataField="LevelId" HeaderText="LevelId" SortExpression="LevelId" />
                       <asp:BoundField DataField="DateHired" HeaderText="DateHired" SortExpression="DateHired" />
                       <asp:BoundField DataField="SpecialityId" HeaderText="SpecialityId" SortExpression="SpecialityId" />
                       <asp:BoundField DataField="StatusId" HeaderText="StatusId" SortExpression="StatusId" />
                   </Columns>
               </asp:GridView>
               <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="select * from
balaji.CapgeminiDetails_HR_Batch4" UpdateCommand="Update balaji.CapgeminiDetails_HR_Batch4 set [Email]=@Email, [LevelId]=@LevelId, [DateHired]=@DateHired, [SpecialityId]=@SpecialityId, [StatusId]=@StatusId where [EmployeeID]=@EmployeeID" DeleteCommand="delete from balaji.CapgeminiDetails_HR_Batch4  where [EmployeeID]=@EmployeeID"></asp:SqlDataSource>
        

               </asp:Panel>
       <asp:Panel ID="Panel2" runat="server">
                   <asp:GridView ID="GridView2" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource3">
                   </asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="select * from
balaji.CapgeminiDetails_HR_Batch4 where [EmployeeId]=@EmployeeID" UpdateCommand="Update balaji.CapgeminiDetails_HR_Batch4 set [Email]=@Email, [LevelId]=@LevelId, [DateHired]=@DateHired, [SpecialityId]=@SpecialityId, [StatusId]=@StatusId where [EmployeeID]=@EmployeeID" DeleteCommand="delete from balaji.CapgeminiDetails_HR_Batch4  where [EmployeeID]=@EmployeeID">
                       <SelectParameters>
                           <asp:ControlParameter ControlID="ddEmployeeID" Name="EmployeeID" PropertyName="SelectedValue" />
                       </SelectParameters>
                   </asp:SqlDataSource>

               </asp:Panel>
               

           </td>
               <td style="width:10%">

           </td>
       </tr>
   </table>
</asp:Content>
