<%@ Page Title="" Language="C#" MasterPageFile="~/HRClerkMaster.Master" AutoEventWireup="true" CodeBehind="EmployeeSearch.aspx.cs" Inherits="HR_PresentationLayer_ASP.NET.EmployeeSearch" %>
<asp:Content ID="Content1" ContentPlaceHolderID="cphBody" runat="server">
    <table>
       <tr>
           <td style="width:10%">

           </td>
           <td style="width:80%">
               <br />
               <table>
                   <tr>
                       <td style="width: 20%">
                           
               
                       </td>
                        <td style="width: auto">
                            <asp:Label runat="server">Search Employee: </asp:Label> 
                            <asp:DropDownList ID="DropDownList1" CssClass="browser-default" Width="200px" runat="server" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged" DataSourceID="SqlDataSource1" DataTextField="EmployeeID" DataValueField="EmployeeID" AutoPostBack="True">
                            </asp:DropDownList>
                            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="
select EmployeeID from balaji.Employee_HR_Batch4"></asp:SqlDataSource>
                       </td>
                       <td>
                           <asp:Button ID="Button1" OnClick="Button1_Click" CssClass="waves-effect waves-light btn" runat="server" Text="Refresh"  />
                       </td>
                       <td>
                          <asp:HyperLink ID="btnAddNew" runat="server" CssClass="waves-effect waves-light btn" Text="Add New" NavigateUrl="~/EmployeeControl.aspx" ></asp:HyperLink>
                       </td>
                   </tr>
               </table>
               <br />
               <asp:Panel ID="Panel1" runat="server">
                   <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BorderWidth="200px" DataKeyNames="EmployeeID" DataSourceID="SqlDataSource2" BorderColor="White">
                       <Columns>
                           <asp:BoundField DataField="EmployeeID" HeaderText="EmployeeID" InsertVisible="False" ReadOnly="True" SortExpression="EmployeeID" />
                           <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" />
                           <asp:BoundField DataField="MiddleName" HeaderText="MiddleName" SortExpression="MiddleName" />
                           <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                           <asp:BoundField DataField="BirthDate" HeaderText="BirthDate" SortExpression="BirthDate" />
                           <asp:BoundField DataField="Age" HeaderText="Age" SortExpression="Age" />
                           <asp:BoundField DataField="Gender" HeaderText="Gender" SortExpression="Gender" />
                           <asp:BoundField DataField="CivilStatusId" HeaderText="CivilStatusId" SortExpression="CivilStatusId" />
                           <asp:BoundField DataField="Religion" HeaderText="Religion" SortExpression="Religion" />
                           <asp:BoundField DataField="Citizenship" HeaderText="Citizenship" SortExpression="Citizenship" />
                           <asp:BoundField DataField="MobileNo" HeaderText="MobileNo" SortExpression="MobileNo" />
                           <asp:BoundField DataField="HomePhoneNo" HeaderText="HomePhoneNo" SortExpression="HomePhoneNo" />
                           <asp:BoundField DataField="Street1" HeaderText="Street1" SortExpression="Street1" />
                           <asp:BoundField DataField="Street2" HeaderText="Street2" SortExpression="Street2" />
                           <asp:BoundField DataField="City" HeaderText="City" SortExpression="City" />
                           <asp:BoundField DataField="UserState" HeaderText="UserState" SortExpression="UserState" />
                           <asp:BoundField DataField="Zip" HeaderText="Zip" SortExpression="Zip" />
                           <asp:BoundField DataField="Country" HeaderText="Country" SortExpression="Country" />
                           <asp:BoundField DataField="ProjectId" HeaderText="ProjectId" SortExpression="ProjectId" />
                           <asp:BoundField DataField="SkillId" HeaderText="SkillId" SortExpression="SkillId" />
                           <asp:BoundField DataField="EducationalBackground" HeaderText="EducationalBackground" SortExpression="EducationalBackground" />
                       </Columns>
                   </asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="
select * from balaji.Employee_HR_Batch4" 
                       UpdateCommand="update balaji.Employee_HR_Batch4 set 
                       [FirstName]=@FirstName, 
                       [MiddleName]=@MiddleName, 
                       [LastName]=@LastName, 
                       [BirthDate]=@BirthDate,
                       [Age]=@Age, [Gender]=@Gender, 
                       [CivilStatusId]=@CivilStatusId, 
                       [Religion]=@Religion,
                       [Citizenship]=@Citizenship,
                       [MobileNo]=@MobileNo,
                       [HomePhoneNo]=@HomePhoneNo,
                       [Street1]=@Street1,
                       [Street2]=@Street2,
                       [City]=@City,
                       [UserState]=@UserState,
                       [Zip]=@Zip,
                       [Country]=@Country,
                       [ProjectId]=@ProjectId,
                       [SkillId]=@SkillId,
                       [EducationalBackground]=@EducationalBackground
                       where
                       [EmployeeID]=@EmployeeID
                          " 
                       DeleteCommand="Delete from balaji.Employee_HR_Batch4 where
                       [EmployeeID]=@EmployeeID"></asp:SqlDataSource>
                   

               </asp:Panel>
               <asp:Panel ID="Panel2" runat="server">
                   <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BorderColor="White" BorderWidth="200px" DataKeyNames="EmployeeID" DataSourceID="SqlDataSource3">
                       <Columns>
                           <asp:BoundField DataField="EmployeeID" HeaderText="EmployeeID" InsertVisible="False" ReadOnly="True" SortExpression="EmployeeID" />
                           <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" />
                           <asp:BoundField DataField="MiddleName" HeaderText="MiddleName" SortExpression="MiddleName" />
                           <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                           <asp:BoundField DataField="BirthDate" HeaderText="BirthDate" SortExpression="BirthDate" />
                           <asp:BoundField DataField="Age" HeaderText="Age" SortExpression="Age" />
                           <asp:BoundField DataField="Gender" HeaderText="Gender" SortExpression="Gender" />
                           <asp:BoundField DataField="CivilStatusId" HeaderText="CivilStatusId" SortExpression="CivilStatusId" />
                           <asp:BoundField DataField="Religion" HeaderText="Religion" SortExpression="Religion" />
                           <asp:BoundField DataField="Citizenship" HeaderText="Citizenship" SortExpression="Citizenship" />
                           <asp:BoundField DataField="MobileNo" HeaderText="MobileNo" SortExpression="MobileNo" />
                           <asp:BoundField DataField="HomePhoneNo" HeaderText="HomePhoneNo" SortExpression="HomePhoneNo" />
                           <asp:BoundField DataField="Street1" HeaderText="Street1" SortExpression="Street1" />
                           <asp:BoundField DataField="Street2" HeaderText="Street2" SortExpression="Street2" />
                           <asp:BoundField DataField="City" HeaderText="City" SortExpression="City" />
                           <asp:BoundField DataField="UserState" HeaderText="UserState" SortExpression="UserState" />
                           <asp:BoundField DataField="Zip" HeaderText="Zip" SortExpression="Zip" />
                           <asp:BoundField DataField="Country" HeaderText="Country" SortExpression="Country" />
                           <asp:BoundField DataField="ProjectId" HeaderText="ProjectId" SortExpression="ProjectId" />
                           <asp:BoundField DataField="SkillId" HeaderText="SkillId" SortExpression="SkillId" />
                           <asp:BoundField DataField="EducationalBackground" HeaderText="EducationalBackground" SortExpression="EducationalBackground" />
                       </Columns>
                   </asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="select * from balaji.Employee_HR_Batch4 where [EmployeeID]=@EmployeeID"
                       UpdateCommand="update balaji.Employee_HR_Batch4 set 
                       [FirstName]=@FirstName, 
                       [MiddleName]=@MiddleName, 
                       [LastName]=@LastName, 
                       [BirthDate]=@BirthDate,
                       [Age]=@Age, [Gender]=@Gender, 
                       [CivilStatusId]=@CivilStatusId, 
                       [Religion]=@Religion,
                       [Citizenship]=@Citizenship,
                       [MobileNo]=@MobileNo,
                       [HomePhoneNo]=@HomePhoneNo,
                       [Street1]=@Street1,
                       [Street2]=@Street2,
                       [City]=@City,
                       [UserState]=@UserState,
                       [Zip]=@Zip,
                       [Country]=@Country,
                       [ProjectId]=@ProjectId,
                       [SkillId]=@SkillId,
                       [EducationalBackground]=@EducationalBackground
                       where
                       [EmployeeID]=@EmployeeID
                          " 
                       DeleteCommand="Delete from balaji.Employee_HR_Batch4 where
                       [EmployeeID]=@EmployeeID">
                       <SelectParameters>
                           <asp:ControlParameter ControlID="DropDownList1" Name="EmployeeID" PropertyName="SelectedValue" />
                       </SelectParameters>
                   </asp:SqlDataSource>
               </asp:Panel>
               

           </td>
               <td style="width:10%">

           </td>
       </tr>
   </table>
</asp:Content>
