<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.Master" AutoEventWireup="true" CodeBehind="LevelSearch.aspx.cs" Inherits="HR_PresentationLayer_ASP.NET.LevelSearch" %>
<asp:Content ID="Content1" ContentPlaceHolderID="cphBody" runat="server">
    <table>
       <tr>
           <td style="width:10%">

           </td>
           <td style="width:80%">
               <br />
               <table>
                   <tr>
                       <td style="width: 128px">
                           <asp:Label runat="server">Search Level: </asp:Label> 
               
                       </td>
                        <td style="width: auto">
                            <asp:DropDownList ID="DropDownList1" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged" CssClass="browser-default" Width="200px" runat="server" AutoPostBack="True" DataSourceID="SqlDataSource1" DataTextField="LevelId" DataValueField="LevelId">
                            </asp:DropDownList>
                            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="select LevelId from balaji.Level_HR_Batch4"></asp:SqlDataSource>
               
                       
                        </td>
                       <td>
                           <asp:Button ID="Button1" CssClass="waves-effect waves-light btn" runat="server" Text="Refresh" OnClick="Button1_Click" />
                       </td>
                       <td>
                          <asp:HyperLink ID="btnAddNew" runat="server" CssClass="waves-effect waves-light btn" Text="Add New" NavigateUrl="~/LevelControl.aspx" ></asp:HyperLink>
                       </td>
                   </tr>
               </table>
               <br />
               <asp:Panel ID="Panel1" runat="server">
                   <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="LevelId" DataSourceID="SqlDataSource2">
                       <Columns>
                           <asp:BoundField DataField="LevelId" HeaderText="LevelId" InsertVisible="False" ReadOnly="True" SortExpression="LevelId" />
                           <asp:BoundField DataField="LevelDescription" HeaderText="LevelDescription" SortExpression="LevelDescription" />
                       </Columns>
                   </asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="
select * from balaji.Level_HR_Batch4" UpdateCommand="update balaji.Level_HR_Batch4 set [LevelDescription]=@LevelDescription where [LevelId]=@LevelId" DeleteCommand="delete from balaji.Level_HR_Batch4 where [LevelId]=@LevelId"></asp:SqlDataSource>
                   

               </asp:Panel>
               <asp:Panel ID="Panel2" runat="server">
                   <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="LevelId" DataSourceID="SqlDataSource3">
                       <Columns>
                           <asp:BoundField DataField="LevelId" HeaderText="LevelId" InsertVisible="False" ReadOnly="True" SortExpression="LevelId" />
                           <asp:BoundField DataField="LevelDescription" HeaderText="LevelDescription" SortExpression="LevelDescription" />
                       </Columns>
                   </asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="select * from balaji.Level_HR_Batch4 where [LevelId]=@LevelId" UpdateCommand="update balaji.Level_HR_Batch4 set [LevelDescription]=@LevelDescription where [LevelId]=@LevelId" DeleteCommand="delete from balaji.Level_HR_Batch4 where [LevelId]=@LevelId">
                       <SelectParameters>
                           <asp:ControlParameter ControlID="DropDownList1" Name="LevelId" PropertyName="SelectedValue" />
                       </SelectParameters>
                   </asp:SqlDataSource>
               </asp:Panel>
               

           </td>
               <td style="width:10%">

           </td>
       </tr>
   </table>
</asp:Content>
