<%@ Page Title="" Language="C#" MasterPageFile="~/HRClerkMaster.Master" AutoEventWireup="true" CodeBehind="Projectsearch.aspx.cs" Inherits="HR_PresentationLayer_ASP.NET.Projectsearch" %>
<asp:Content ID="Content1" ContentPlaceHolderID="cphBody" runat="server">
    <table>
       <tr>
           <td style="width:10%">

           </td>
           <td style="width:80%">
               <br />
               <table>
                   <tr>
                       <td style="width: 128px">
                           <asp:Label runat="server">Search Project: </asp:Label> 
               
                       </td>
                        <td style="width: auto">
                            <asp:DropDownList OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged" ID="DropDownList1" CssClass="browser-default" Width="200px" runat="server" DataSourceID="SqlDataSource1" DataTextField="ProjectID" DataValueField="ProjectID" AutoPostBack="True">
                            </asp:DropDownList>
                            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="select ProjectID from balaji.Project_HR_Batch4"></asp:SqlDataSource>
                       </td>
                       <td>
                           <asp:Button OnClick="Button1_Click" ID="Button1" CssClass="waves-effect waves-light btn" runat="server" Text="Refresh"  />
                       </td>
                       <td>
                          <asp:HyperLink ID="btnAddNew" runat="server" CssClass="waves-effect waves-light btn" Text="Add New" NavigateUrl="~/ProjectControl.aspx" ></asp:HyperLink>
                       </td>
                   </tr>
               </table>
               <br />
               <asp:Panel ID="Panel1" runat="server">
                   <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="ProjectID" DataSourceID="SqlDataSource2">
                       <Columns>
                           <asp:BoundField DataField="ProjectID" HeaderText="ProjectID" InsertVisible="False" ReadOnly="True" SortExpression="ProjectID" />
                           <asp:BoundField DataField="ProjectName" HeaderText="ProjectName" SortExpression="ProjectName" />
                           <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                           <asp:BoundField DataField="Client" HeaderText="Client" SortExpression="Client" />
                           <asp:BoundField DataField="StartDate" HeaderText="StartDate" SortExpression="StartDate" />
                           <asp:BoundField DataField="EndDate" HeaderText="EndDate" SortExpression="EndDate" />
                       </Columns>
                   </asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="select * from balaji.Project_HR_Batch4"
                       UpdateCommand="Update balaji.Project_HR_Batch4 set [ProjectName]=@ProjectName, [Description]=@Description, [Client]=@Client, [StartDate]=@StartDate, [EndDate]=@EndDate where  [ProjectID]=@ProjectID "
                       DeleteCommand="Delete from balaji.Project_HR_Batch4 where [ProjectID]=@ProjectID"
                       ></asp:SqlDataSource>
                   

               </asp:Panel>
               <asp:Panel ID="Panel2" runat="server">
                   <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="ProjectID" DataSourceID="SqlDataSource3">
                       <Columns>
                           <asp:BoundField DataField="ProjectID" HeaderText="ProjectID" InsertVisible="False" ReadOnly="True" SortExpression="ProjectID" />
                           <asp:BoundField DataField="ProjectName" HeaderText="ProjectName" SortExpression="ProjectName" />
                           <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                           <asp:BoundField DataField="Client" HeaderText="Client" SortExpression="Client" />
                           <asp:BoundField DataField="StartDate" HeaderText="StartDate" SortExpression="StartDate" />
                           <asp:BoundField DataField="EndDate" HeaderText="EndDate" SortExpression="EndDate" />
                       </Columns>
                   </asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="select * from balaji.Project_HR_Batch4 where [ProjectID]=@ProjectID"
                         UpdateCommand="Update balaji.Project_HR_Batch4 set [ProjectName]=@ProjectName, [Description]=@Description, [Client]=@Client, [StartDate]=@StartDate, [EndDate]=@EndDate where  [ProjectID]=@ProjectID "
                       DeleteCommand="Delete from balaji.Project_HR_Batch4 where [ProjectID]=@ProjectID"
                     
                       >
                       <SelectParameters>
                           <asp:ControlParameter ControlID="DropDownList1" Name="ProjectID" PropertyName="SelectedValue" />
                       </SelectParameters>
                   </asp:SqlDataSource>
               </asp:Panel>
               

     
               

           </td>
               <td style="width:10%">

           </td>
       </tr>
   </table>
</asp:Content>
