<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.Master" AutoEventWireup="true" CodeBehind="RolesSearch.aspx.cs" Inherits="HR_PresentationLayer_ASP.NET.RolesSearch" %>
<asp:Content ID="Content1" ContentPlaceHolderID="cphBody" runat="server">
    <table>
       <tr>
           <td style="width:10%">

           </td>
           <td style="width:80%">
               <br />
               <table>
                   <tr>
                       <td style="width: 128px">
                           <asp:Label runat="server">Search Role: </asp:Label> 
               
                       </td>
                        <td style="width: auto">
                            <asp:DropDownList ID="DropDownList1" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged" CssClass="browser-default" Width="200px" runat="server" DataSourceID="SqlDataSource1" DataTextField="RoleId" DataValueField="RoleId" AutoPostBack="True">
                            </asp:DropDownList>
                            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="
select RoleId from balaji.Roles_HR_Batch4"></asp:SqlDataSource>
                       </td>
                       <td>
                           <asp:Button ID="Button1" CssClass="waves-effect waves-light btn" runat="server" Text="Refresh" OnClick="Button1_Click"/>
                       </td>
                       <td>
                          <asp:HyperLink ID="btnAddNew" runat="server" CssClass="waves-effect waves-light btn" Text="Add New" NavigateUrl="~/RolesControl.aspx" ></asp:HyperLink>
                       </td>
                   </tr>
               </table>
               <br />
               <asp:Panel ID="Panel1" runat="server">
                   <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="RoleId" DataSourceID="SqlDataSource2">
                       <Columns>
                           <asp:BoundField DataField="RoleId" HeaderText="RoleId" InsertVisible="False" ReadOnly="True" SortExpression="RoleId" />
                           <asp:BoundField DataField="RoleName" HeaderText="RoleName" SortExpression="RoleName" />
                       </Columns>
                   </asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="
select * from balaji.Roles_HR_Batch4" UpdateCommand="update balaji.Roles_HR_Batch4 set [RoleName]=@RoleName where [RoleId]=@RoleId" DeleteCommand="delete from balaji.Roles_HR_Batch4 where [RoleId]=@RoleId"></asp:SqlDataSource>
                   

               </asp:Panel>
               <asp:Panel ID="Panel2" runat="server">
                   <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" DataKeyNames="RoleId" DataSourceID="SqlDataSource3" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                       <Columns>
                           <asp:BoundField DataField="RoleId" HeaderText="RoleId" InsertVisible="False" ReadOnly="True" SortExpression="RoleId" />
                           <asp:BoundField DataField="RoleName" HeaderText="RoleName" SortExpression="RoleName" />
                       </Columns>
                   </asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="
select * from balaji.Roles_HR_Batch4 where [RoleId]=@RoleId"  UpdateCommand="update balaji.Roles_HR_Batch4 set [RoleName]=@RoleName where [RoleId]=@RoleId" DeleteCommand="delete from balaji.Roles_HR_Batch4 where [RoleId]=@RoleId">
                       <SelectParameters>
                           <asp:ControlParameter ControlID="DropDownList1" Name="RoleId" PropertyName="SelectedValue" />
                       </SelectParameters>
                   </asp:SqlDataSource>
               </asp:Panel>
               

           </td>
               <td style="width:10%">

           </td>
       </tr>
   </table>
</asp:Content>
