<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.Master" AutoEventWireup="true" CodeBehind="SpecialitySearch.aspx.cs" Inherits="HR_PresentationLayer_ASP.NET.SpecialitySearch" %>
<asp:Content ID="Content1" ContentPlaceHolderID="cphBody" runat="server">
    <table>
       <tr>
           <td style="width:10%">

           </td>
           <td style="width:80%">
               <br />
               <table>
                   <tr>
                       <td style="width: 128px">
                           <asp:Label runat="server">Search Speciality: </asp:Label> 
               
                       </td>
                        <td style="width: auto">
                            <asp:DropDownList ID="ddSpecialityID" CssClass="browser-default" Width="200px" OnSelectedIndexChanged="ddSpecialityID_SelectedIndexChanged" runat="server" DataSourceID="SqlDataSource1" DataTextField="SpecialityID" DataValueField="SpecialityID" AutoPostBack="True">
                            </asp:DropDownList>
               
                       
                            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="select SpecialityID from balaji.Speciality_HR_Batch4"></asp:SqlDataSource>
               
                       
                        </td>
                       <td>
                           <asp:Button ID="Button1" CssClass="waves-effect waves-light btn" runat="server" Text="Refresh" OnClick="Button1_Click" />
                       </td>
                       <td>
                          <asp:HyperLink ID="btnAddNew" runat="server" CssClass="waves-effect waves-light btn" Text="Add New" NavigateUrl="~/SpecialityControl.aspx" ></asp:HyperLink>
                       </td>
                   </tr>
               </table>
               <br />
               <asp:Panel ID="Panel1" runat="server">
                   <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="SpecialityID" DataSourceID="SqlDataSource2">
                       <Columns>
                           <asp:BoundField DataField="SpecialityID" HeaderText="SpecialityID" InsertVisible="False" ReadOnly="True" SortExpression="SpecialityID" />
                           <asp:BoundField DataField="SpecialityName" HeaderText="SpecialityName" SortExpression="SpecialityName" />
                       </Columns>
                   </asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="select * from balaji.Speciality_HR_Batch4" UpdateCommand="update balaji.Speciality_HR_Batch4 set [SpecialityName]=@SpecialityName where [SpecialityID]=@SpecialityID" DeleteCommand="delete from balaji.Speciality_HR_Batch4 where [SpecialityID]=@SpecialityID"></asp:SqlDataSource>
                   

               </asp:Panel>
               <asp:Panel ID="Panel2" runat="server">
                   <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="SpecialityID" DataSourceID="SqlDataSource3">
                       <Columns>
                           <asp:BoundField DataField="SpecialityID" HeaderText="SpecialityID" InsertVisible="False" ReadOnly="True" SortExpression="SpecialityID" />
                           <asp:BoundField DataField="SpecialityName" HeaderText="SpecialityName" SortExpression="SpecialityName" />
                       </Columns>
                   </asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="select * from balaji.Speciality_HR_Batch4 where [SpecialityID]=@SpecialityID"  UpdateCommand="update balaji.Speciality_HR_Batch4 set [SpecialityName]=@SpecialityName where [SpecialityID]=@SpecialityID" DeleteCommand="delete from balaji.Speciality_HR_Batch4 where [SpecialityID]=@SpecialityID">
                       <SelectParameters>
                           <asp:ControlParameter ControlID="ddSpecialityID" Name="SpecialityID" PropertyName="SelectedValue" />
                       </SelectParameters>
                   </asp:SqlDataSource>
               </asp:Panel>
               

           </td>
               <td style="width:10%">

           </td>
       </tr>
   </table>

</asp:Content>
