<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.Master" AutoEventWireup="true" CodeBehind="UsersSearch.aspx.cs" Inherits="HR_PresentationLayer_ASP.NET.UsersSearch" %>
<asp:Content ID="Content1" ContentPlaceHolderID="cphBody" runat="server">
    <table>
       <tr>
           <td style="width:10%">

           </td>
           <td style="width:80%">
            
               <table>
                    <tr>
                       <td colspan="4">
                           <h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Manage Users</h3>
                       </td>
                   </tr>
                   <tr>
                       <td style="width: auto">
                           <asp:Label runat="server">Search User: </asp:Label> 
               
                       </td>
                        <td style="width: auto">
                            <asp:DropDownList runat="server" ID="ddUserName" CssClass="browser-default" Width="200px" DataSourceID="SqlDataSource1" DataTextField="UserName" DataValueField="UserName" OnSelectedIndexChanged="ddUserName_SelectedIndexChanged1" AutoPostBack="True"></asp:DropDownList>
               
                       
                            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="select UserName from balaji.Users_HR_Batch4;"></asp:SqlDataSource>
               
                       
                        </td>
                       <td>
                           <asp:Button ID="Button1" CssClass="waves-effect waves-light btn" runat="server" Text="Refresh" OnClick="Button1_Click1"  />
                       </td>
                       <td>
                          <asp:HyperLink ID="btnAddNew" runat="server" CssClass="waves-effect waves-light btn" Text="Add New" NavigateUrl="~/UsersControl.aspx" ></asp:HyperLink>
                       </td>
                   </tr>
               </table>
               <br />
               <asp:Panel ID="Panel1" runat="server">
                   <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="UserId" DataSourceID="SqlDataSource2">
                       <Columns>
                           <asp:BoundField DataField="UserId" HeaderText="UserId" InsertVisible="False" ReadOnly="True" SortExpression="UserId" />
                           <asp:BoundField DataField="UserName" HeaderText="UserName" SortExpression="UserName" />
                           <asp:BoundField DataField="UserPassword" HeaderText="UserPassword" SortExpression="UserPassword" />
                           <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" />
                           <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                       </Columns>
                   </asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="select * from balaji.Users_HR_Batch4;" UpdateCommand="update balaji.Users_HR_Batch4 set [UserName]=@UserName, [UserPassword]=@UserPassword, [FirstName]=@FirstName, [LastName]=@LastName where [UserId]=@UserId " DeleteCommand="delete from balaji.Users_HR_Batch4 where [UserId]=@UserId" ></asp:SqlDataSource>
                   

               </asp:Panel>
               <asp:Panel ID="Panel2" runat="server">
                   <asp:GridView ID="GridView2" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource3">
                   </asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="select * from balaji.Users_HR_Batch4 where [UserName]=@UserName" UpdateCommand="update balaji.Users_HR_Batch4 set [UserName]=@UserName, [UserPassword]=@UserPassword, [FirstName]=@FirstName, [LastName]=@LastName where [UserId]=@UserId " DeleteCommand="delete from balaji.Users_HR_Batch4 where [UserId]=@UserId" >
                       <SelectParameters>
                           <asp:ControlParameter ControlID="ddUserName" Name="UserName" PropertyName="SelectedValue" />
                       </SelectParameters>
                   </asp:SqlDataSource>
               </asp:Panel>
               

           </td>
               <td style="width:10%">

           </td>
       </tr>
   </table>
    

</asp:Content>
