<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.Master" AutoEventWireup="true" CodeBehind="UsersSearch.aspx.cs" Inherits="HR_PresentationLayer_ASP.NET.UsersSearch" %>
<asp:Content ID="Content1" ContentPlaceHolderID="cphBody" runat="server">
    <table>
       <tr>
           <td style="width:20%">

           </td>
           <td style="width:80%">
               <br />
               <table>
                   <tr>
                       <td style="width: 113px">
                           <asp:Label runat="server">Search User: </asp:Label> 
               
                       </td>
                        <td>
                            <asp:DropDownList runat="server" ID="ddUserName" CssClass="browser-default" Width="200px" DataSourceID="SqlDataSource2" DataTextField="UserName" DataValueField="UserName" AutoPostBack="True" OnSelectedIndexChanged="ddUserName_SelectedIndexChanged"></asp:DropDownList>
               
                       
                            <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:masterConnectionString %>" SelectCommand="select UserName from balaji.Users_HR_Batch4;
"></asp:SqlDataSource>
               
                       
                        </td>
                       <td>
                           <asp:Button ID="Button1" runat="server" Text="Refresh" OnClick="Button1_Click" />
                       </td>
                   </tr>
               </table>
               <br />
               <asp:Panel ID="Panel1" runat="server">
                   <asp:GridView runat="server" ID="gvUsers" AutoGenerateColumns="False" DataKeyNames="UserId" DataSourceID="SqlDataSource1" CssClass="browser-default" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowSorting="True" CellPadding="4" ForeColor="#333333" GridLines="None">
                   <AlternatingRowStyle BackColor="White" />
    <Columns>
        <asp:BoundField DataField="UserId" HeaderText="UserId" InsertVisible="False" ReadOnly="True" SortExpression="UserId" />
        <asp:BoundField DataField="UserName" HeaderText="UserName" SortExpression="UserName" />
        <asp:BoundField DataField="UserPassword" HeaderText="UserPassword" SortExpression="UserPassword" />
        <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" />
        <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
    </Columns>
                   <EditRowStyle BackColor="#2461BF" />
                   <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                   <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                   <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                   <RowStyle BackColor="#EFF3FB" />
                   <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                   <SortedAscendingCellStyle BackColor="#F5F7FB" />
                   <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                   <SortedDescendingCellStyle BackColor="#E9EBEF" />
                   <SortedDescendingHeaderStyle BackColor="#4870BE" />
</asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:masterConnectionString %>" SelectCommand="select * from balaji.Users_HR_Batch4" UpdateCommand="update balaji.Users_HR_Batch4 set [UserName]=@UserName, [UserPassword]=@UserPassword, [FirstName]=@FirstName, [LastName]=@LastName  where [UserId]=@UserId" DeleteCommand="delete from balaji.Users_HR_Batch4 where [UserId]=@UserId "></asp:SqlDataSource>

               </asp:Panel>
               <asp:Panel ID="Panel2" runat="server">
                   <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CaptionAlign="Bottom" DataKeyNames="UserId" DataSourceID="SqlDataSource3">
                       <Columns>
                           <asp:BoundField DataField="UserId" HeaderText="UserId" InsertVisible="False" ReadOnly="True" SortExpression="UserId" />
                           <asp:BoundField DataField="UserName" HeaderText="UserName" SortExpression="UserName" />
                           <asp:BoundField DataField="UserPassword" HeaderText="UserPassword" SortExpression="UserPassword" />
                           <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" />
                           <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                       </Columns>
                   </asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:masterConnectionString %>" SelectCommand="select * from balaji.Users_HR_Batch4 where ([UserName]=@UserName)">
                       <SelectParameters>
                           <asp:ControlParameter ControlID="ddUserName" Name="UserName" PropertyName="SelectedValue" />
                       </SelectParameters>
                   </asp:SqlDataSource>
               </asp:Panel>
               

           </td>
       </tr>
   </table>
    

</asp:Content>
